### ISSUE TITLE
TS declarations

### ISSUE THREAD

**Issue by stschindler** [darioackermann/saml2-js#6]
Do you plan on migrating the TS declarations as well? Old ones could be found at @types/saml2-js

**Comment by darioackermann** [comment]
I have never done that before but willing to do it :)
 I assume correctly that I can take them from there and modify the module name? (since the underlying code has not been changed)

**Comment by darioackermann** [comment]
I‘ll be closing this issue as stale due to the missing reply for almost two years. If this is still something you need, please reopen.
